[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "2127f717dd1d5b7c41d1774f847c273cb5ffa694"
libgfortran_version = "5.0.0"
os = "macos"

    [[Modflow6.download]]
    sha256 = "62aae2240a8e2f1b84a5c58491acd8300ebc35a9c41a99981ea958f550a3df70"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "8d426e3f75962a9a5bcacfd8ffdaa4d23916536d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "1d526d32c582f45f1b789ea02660dcd393b31e4c14819767c90a56b39667309a"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "031bc5b08bf0359c02283a99b60dc40e4cf75fd0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "d3ae56bdb9f2a7c19f13dcc11bda699b4ebbdb62b86828e40ee687381440f58f"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "cd4034aeba9dd3c383618ec9641d98d9450ef50d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "68a0675e1204ef684fdf531a7dd91724fa6cb037b335f5742dc5e0310b670329"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "73bb0e7e3445ae5d9fd267c74ef9e9927daf6b1d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "81cf5435d6511065ae5245cb00c84f70eba6452e9cc16a1248d2c86ff93a47f9"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "2344aeb402480ee205a541478354eed1dc4b3196"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "b48b65ca77acf4d32ecf6e4dd7bffb8092138d3b224e6090132cb17167c054e7"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "fdc1cec5b72bf37d40749cc58b8d3de73f585b91"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "4993c94d5d8b0f4505103be67aa93565c8cb0f0484f8c747fbc9214bddf392e4"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b1cbd98f8a5299b36f55bc4bd8ff55008e6a517"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "678d16e75d9b1a2437d227dd27bec39203f675d72ad6f41e72a89edd866959e9"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d19491d28e49ff4f6deac29e53dca2265ba9c77"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "5866aede3444d1ac3b2e967afeda0159b1a9def9af2ca7f23131b2484608cdd4"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "491cd4e0362dfd938faa110681316d60bb8bc93c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "2ebb01f9f877a8dddaf46f355ccc2d10b716ebdc323ecaea77931e1ce9d7a2fb"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a413d085fee1247f1b096ebfb152b332135c85ca"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "a1590a03e0537e7b1d5ff099209289ed14b9b345a9be36aacf120f7fddb11a72"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e4b808a57c56ff2b0fdf91df258b6c8cf157670c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "738aa1ffaae6ad72c7f88b758d6c9272e04e3d6cf3cb65c9671b2114aa78a62b"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3e961011bc63e0c20203f473911507ff70f49b60"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "dfbc73911445c03d089b9c680f2df26585f407c995309194290a9cd09971e9ee"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7f297fdc659cb80359392b81ac37d93cf38d96e7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "5f937e20bd23df2299a4e7d96ddf4e103ae23fa0bfd4800ff1c597d57fee25c6"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3f3e23c69adceeb236b0cf70391cfad054ca0172"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "2db64031ec6c8bfee869d83074bfa66248217e5fe56dd80dfb614ce3f403c80c"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03b666aba5b48b7ba3c5453cde1624396a471899"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "a71ec19ea0171fe25d0a0a340329aadaef0b0cd84449dbd96364a7e106b3df64"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "118cd4c27db2630ff3b05d8441db159f77401233"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "bf3173f7a612c64981365fc565d06b363d858a9195c00264e39bac3139ce2d3d"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9c5c567b9ee49ee70589eb3c2ca99f9fe934c404"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "975d275a4ffdc6d9091c2694d23b0f760c9a4d1c785b02839f355f54ed3b277e"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d23aad7ba50aa213164d63a2ab67eeb2450a71cb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "d81e48556ead9024455b74ced0ed3e6a502a619f659078098bdd48658df2a21b"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "162450f1f84e07673328f204ba53a1d9376e3990"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "46e1d6d14028ad4ad7b3f961b20be6a3bd984cc9dd9b5ed3900dd100eae6914b"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.i686-linux-gnu-libgfortran3.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "93c871fd0e83797b4cce838a1a58fc60f3eaeff4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "0f8d878822eb4f9bc7a535208a6f02f30b6fff54a83bfa17f29b333b6b792531"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.i686-linux-gnu-libgfortran4.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "81d2f3f6447eb1ad2fd78fb095de7283194364fc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "bd9f88092a772736ba7061b50cf7ed0ac0506492dee84797e2c2366a605df178"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.i686-linux-gnu-libgfortran5.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "89b12bf5b0db9f3e488d1f3c20ee3f101face4e6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "a1834c7200696eade2c83c9c48d9f60047176c01ff2a7660cbc1cc90bc116071"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.i686-linux-musl-libgfortran3.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "fd7db4a1da47c5ee19a615d78baa7011faac12e1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "46612d5b5b3c75b04f87c43ed0a6c00a082aac065d2866eae0b02a3431fa4529"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.i686-linux-musl-libgfortran4.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "1b1897ec44d88dbb55e67c29f9f764dc6ffcd372"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "96c4a0956067dcd838be40561a4f0da00b40b015951caedc7244779595258edf"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.i686-linux-musl-libgfortran5.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "ba489475621fd8cff756f3b08ce424d7bec94845"
libgfortran_version = "3.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "6c1792be649105d13b7bd51a5f96c4f60a0e2b406cf6352eb815fc4fd1cb5168"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "dfd8223761e51a37f21bc83d2ea136fff66b00e9"
libgfortran_version = "4.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "62723a0f28cd92449e502e27bb02c629dd8beaac20a6efdfeeeed22bfb7fc9b2"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "79de7ca8dd9e7fed84b1156c13dc8ec4dc4631c9"
libgfortran_version = "5.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "b04b12f0d323f5ad3daeb12a3a1b118feb347e5e296654b0907725706937cbd0"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[Modflow6]]
arch = "powerpc64le"
git-tree-sha1 = "de8bdf3b09f5875935770155202cfb67edbb5009"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "2f1284a21321e8cb8ad2ecef34e307f6590491b32758bc533a454f7d87aa4b5c"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Modflow6]]
arch = "powerpc64le"
git-tree-sha1 = "2daee72bb3639d1113df0382d885555bc5056ce3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "3adbea03f7f426684c02aea33d0d9268d6cd21ac4bcc0dd71279cf3ff7b98304"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Modflow6]]
arch = "powerpc64le"
git-tree-sha1 = "79630165c5e52b9458a9bef3c31e096328f83009"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "053c52b4a31a43ed10eed8240602f11f4823d6f52e78b210521f1a87b2ba86e9"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "145cd110e12a64f95d1f95c33e3dac499cf2fb06"
libgfortran_version = "3.0.0"
os = "macos"

    [[Modflow6.download]]
    sha256 = "c40c50826fea6891d3794f41cf178ec8b78f871acbdbde6f28d658e61b60b4d2"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "04ed122c22db3fb7ba2958847af269661e4a41dd"
libgfortran_version = "4.0.0"
os = "macos"

    [[Modflow6.download]]
    sha256 = "9683cbcb22b046d754597681bd3322837999bebcaed61683551a1aa79f20779e"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "1c44d5163caf601c4ab3e59f1184ebb585bfe1dd"
libgfortran_version = "5.0.0"
os = "macos"

    [[Modflow6.download]]
    sha256 = "dd95939a84498f90ed6227a6a9bddac8039b6f39e871847304fcdb288a751a9b"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "2544026ffc9245843497390a58fe2c8de41cbd42"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "b067a15d719fccbc26fe349b4892577a8fa8f8ffd2e96b1fab22c89c7187af83"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "813c4c6247ddb228d7ffaf1d8db2d3cb33d03395"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "a959d8065d8f754f464f11b55769ac0282f4f71fa2d62c8db34770b17ae7b60d"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "b7ab4ef42454a564acd29ba53bc54cca1eddc891"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "7eaf19e6d4bf33845ae55350e891b60b78fdffc65b0f852127093020362c3b65"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "709b32c523177ee61334ba033f91fca94d321b82"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "420ca4f0f595977561d3b5541a07a4ecb21a55c807084d27e263a00e8a49f9a2"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "a98f54cb06470bf1bd4d6c664a057f8f5f3d2e9c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "078b5fc584813463ce9bc357729cd26cd0826d2f13de91853046c375352b234c"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "8bd3e41ed97e31473ebd70a52cf76565d0333dd9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "45f19e172ffdcce3c0b9a42921c90944386962e41f70c0c25413ba7ef0133b3a"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "d5e466bd613353458ea2123a7699966fb6f6379c"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Modflow6.download]]
    sha256 = "d7af26f78970c18d420366e83b996ac19dd0a42fba71e391236afddeb9ff5216"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "85cffcd30bb59547e5ce4a1085e94c89547b9fad"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Modflow6.download]]
    sha256 = "1a97e542fad47496380c5e380c91151e6003cd028163319f1bd6c60c4401425e"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "0ed84b1e0f7fc5ca4b617afe674f719814c5f0de"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Modflow6.download]]
    sha256 = "8c23f8999a3aadddf9df992f41a7b3d81c70f978d0ccea505bbc3928e320b182"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "5ed77b6c9049d9fed8d6996a51c41475fd6bd00d"
libgfortran_version = "3.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "46ef6a0d18fb01514c0f59e53b5e692c536e82e8072a566dd4067fa11c7262ae"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "a1580ad9c11164a995d7ef90499c1d824dc18271"
libgfortran_version = "4.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "0e172f5d452ab3dbe125600b3c35065dbf17ea6f1e5e01956756254ac78bd198"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "3a2f6b478455918a17eb4b2985d19f85189b5640"
libgfortran_version = "5.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "4e8802be9f61c18026122dde2acf540b67a1631a4e2bf6123ecf341919f10eae"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.2.2+0/Modflow6.v6.2.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
