[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "2328827cfedafaa431a5b1df2f9c31d6134b98a2"
libgfortran_version = "5.0.0"
os = "macos"

    [[Modflow6.download]]
    sha256 = "8e29c16a9b3f457f6b66a049dd47eb6e22dd30f8edf68a3c3fb428bd322a975e"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "59ca208fd640e357604c4f1490937600e6588b97"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "60576452def550fe65db39dd8c75f0bad08c74ba3d244c2ae63e238de5395f86"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "6b2f0aa6e5435d42dcf7f662f351c6da3933213f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "298c7bf31c65140f8032f920e4f42d8f4bd455b8bd4727fe2d17dfee7895111e"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "2900748117280b7e015a02ed6bd7c42d4850837c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "e36a793ce7f1d57d5f12d49d904b72c0d1adf315397adf3c6352f6d0bedf0548"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "6b16644f1c73336aa431b940c9f6bc3e41f37155"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "15c9b6b4604adc5cba2d8beeda3fdd877ca6c53784b9b876bac499a714dddf32"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "7dc67fb2202465191de9bc9a68b43da11208bf0d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "236a9b8885119709782f5ed9c97cad05338bbcf1afba1049dda0b9bc0d886235"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Modflow6]]
arch = "aarch64"
git-tree-sha1 = "764ea59c8eb86f9df19a0143e24469961cbbf3bf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "5d0ed5bf3b39dafed8af5b9c8592e7083af3c90e56e71587bb61d19030883ca6"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "14359e558bfafce7bfe21c81f03ad803f2ecbbd5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "fb3582d31288a76ae38adab16b4e31eb11b3d87fea122e7347eb8455f6658bc0"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5649e5d68207493f03b71ea3cd016aab792f211a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "9cc79881b3543fe694196180db129c706c88c62246419899c328f71d90db4e2c"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0a0394f93f0d4e71ad3ddaf85c2218151399b367"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "9f30b597e2345ff15f95b912a163a2a3a40bb4681cff6c8d6ea052f081c3652e"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8f4c91de68bd9d62ebdc9a847e05978fe4ab8c69"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "fc77e338ae6397e447aabaf6f11dde7e7bf4bac4c9e776a82112b45b82df2a5d"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1c162ba0de60a87b4dadb1c7b7c488488a2846dc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "ab8b45f134d92fb85f5292181c35ce0a37aa97fc650325a1509c33280ab4b948"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Modflow6]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1dae96bda908be8bc36745a1750a03c2661c1cd3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "97042d480d6fd0f879d4410391d177d3f695676fa97fe8e3f1439c40c5d5720a"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be12038384c56c941a63de120d0ef4943a475141"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "f8fe1c834b84b6b65948c91ffbdec9ce78f57b430c9c0ca913ba9fc8e37d57ed"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4dd874b9b1c227d4607eb0fece92aebcd670339b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "6d5034398d2ae91759014ecd528cadf9b22ecfdb974911cf3df432f5e60c5406"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "29f6ccefd165544bc36a214f8cf10d6809b9f6b1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "0b2585b3865ee07094772d2454a18e1279e0b045398e0d1f0c1f1b8d38496607"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "62b454cf512f05b92f3ed8eb93e8e5238bc19522"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "f2cd7975dcc907309d371394ce33666ee583e2756d00a2478d83c5a2c1c7afe0"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "115ce42a58477e1d6defaff8c55512f773006e0e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "fc48b6f61a5c0a256c7a41afc96ee328f424c46af8117d734ac321cce2adc3ea"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Modflow6]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb36d41222f3ef3476e675ebe19faec1e7a32fa7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "eec3cdeea08abb624d38cb8aa6d27e888d9dd0a12dba47312cbbf8417b6c0573"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "b83e383d773d1256eede99a95cf060f7a84a2286"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "870d7a55db146ef15159ae5017e4f81c68481618afa64777a977f59d352d042a"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "00c84d139e621908b0b2b64dcdca545c5258dd31"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "ca387868cee0a9894d96a4fad1985dd0d5a09ff5a8c217fd08409e412dbcf724"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "9df47fc0989f4178b788f82e3cebf574753c6bea"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "936e7633cbacb274877fce19bd57ec544431022fbea1a9552dc3b6d8e4ea4d07"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "c22b73e80bf612298504a7fddd19f208361464ea"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "19657f23e9c842de38d86ea7c07af52b2e94e9dff824a6fcd6396c5f34aa55d7"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.i686-linux-musl-libgfortran3.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "3e9c452758180001d4d2a3977bc1c49627e0086c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "4fecf2a017d73d1543d0c415b23ba5519d254b7fe2c70c7098a28dfa9019ddce"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.i686-linux-musl-libgfortran4.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "024a83fb96a52151fe8e4a49c2ec04d2c48501c4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "ca031189795f9165febe59b062ec1c6fc82da9abf546c44ece408e8780927446"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.i686-linux-musl-libgfortran5.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "beb9f327c049621cbc39d8997963075cb6cb296b"
libgfortran_version = "3.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "cf1e07f3ad8018bd1c5c45b46417a9b91c29fd7e65bbf24918548d52b95f5817"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "e33f52e08d0552b00ccf49cef9f351056aaf87cc"
libgfortran_version = "4.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "531c1923f466e9535e9482c6718ebb7e58f2c08e428e310b70b93b2ea97c5ea7"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Modflow6]]
arch = "i686"
git-tree-sha1 = "84d3391c0101786191060a9829383c0e2dbe356d"
libgfortran_version = "5.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "978de212d0ee741aa1989fb3729d6cf8aa3a7eb57b46e79e8408ab36256ec76b"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Modflow6]]
arch = "powerpc64le"
git-tree-sha1 = "06d2228de27b44643d2b2a98a7041eadad1af430"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "67029364b2e8b76e6edf299e053c9e8b23067eb6dc4095d946cec2aa481af2ad"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Modflow6]]
arch = "powerpc64le"
git-tree-sha1 = "3bdc995b3dbeb7bc38e3f2c0ca581a3ae87f6895"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "c657e769f14f92c67de5d5def213c659a10114efc0ad2f6480b6f68bc2764054"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Modflow6]]
arch = "powerpc64le"
git-tree-sha1 = "d34abdad845334f074e1b800903291d52683923b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "25938773b3be2375f5e51897d7b6511e5bff60e92a0af96e65f81c6b421f169c"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "2c5e6215cc4a9754d3e048884d1b31160663e973"
libgfortran_version = "3.0.0"
os = "macos"

    [[Modflow6.download]]
    sha256 = "da33c3cb658610c7421e2b11510017bcaab5deb2ac0796089c2f59d0f066fd6d"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "37ce2b074977d7e8505bf0b46a17208145800f27"
libgfortran_version = "4.0.0"
os = "macos"

    [[Modflow6.download]]
    sha256 = "d19999572d0658dffcef9e32a6434afc4322e77c139e47554783f09c1aee3eb5"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "529d2ac70f68cb92a0fe624817c2d4ded25d48e8"
libgfortran_version = "5.0.0"
os = "macos"

    [[Modflow6.download]]
    sha256 = "57cc7a223edb3fa3d06bc1b4fca2aea1975df1f2f292bb36654f1747a0e2d88d"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "efeec59f2d236a5182960d3fb5eacf5b58ecc3de"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "8b095f74c5f9e457c6378661e39cbc64df4f96e8ef40cdeb3aa54f49c34a889d"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "0f66fd08b05fa3f29306f2f7022c8b8080f5fce0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "c0e1818d894914e5a5721e5be85be830b541cce974af54c285fcb28f956a220c"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "77d38efc1ad7318614073b30c348927ce3435846"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "4cd6a65b8c9f66c23a6db9e768a58a6ac4a037d298ed2dbe729823e315920052"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "dc57346ab4e30fe40bd156d08635553bc79eba0e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "a645060da84965bb636d6941f3f5d70694edfbffeb83e6e5332262a082a8a70e"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "e1f168173ddc9a0e4e9875f2411aecc6d75e6015"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "5424c72f9935150c6416e0f775fbc32c7d32242eed79aa5374773db7fa695139"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "6c97655d7afcdbd532e93f87d365134aaf99de6c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Modflow6.download]]
    sha256 = "256016086e2faafe23243f5c80f5fba24537040fa598888ecaf4be50583e8af7"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "edc865e1af3d02c43ddf01b5c4937006674b8ef1"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Modflow6.download]]
    sha256 = "c0b80498d65205f7a084dde56d44bcaf0050ac633e41046013eeb5350d4abb13"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "70c99b7717232661fb9ba9be8fd6fadeabbf3714"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Modflow6.download]]
    sha256 = "3198f482253af6f21e8c5816b2c8e86641ea3e7cb78fed1d80302c930b24edaf"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "e503cf9df02be47c314216f1f10420e415e437ad"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Modflow6.download]]
    sha256 = "370bccae5497c79c9f6dade39568c86fdfc0bf4c0f53acfe3543b1374d9949b9"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "c411fc20a7f4864093046bd861a93190952727c6"
libgfortran_version = "3.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "7f8984fcaa157667ffb3171651dd2860aa5475c4a23d70c6feb1b30e05e110e2"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "ae9bcb224dd6ae52cd6bd65f0676adab7933cdc9"
libgfortran_version = "4.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "a4afe22fefc455dd8d32162f48f6a6cfe2bb8048a2840edb97873bc854d62f2d"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Modflow6]]
arch = "x86_64"
git-tree-sha1 = "576ad9662745e57df95a1d9339aeb738f0721a0d"
libgfortran_version = "5.0.0"
os = "windows"

    [[Modflow6.download]]
    sha256 = "d8922e9a2a7f897ccd4b432eb045482a6fe4c8ad9173268ada918acf5ee49b1f"
    url = "https://github.com/JuliaBinaryWrappers/Modflow6_jll.jl/releases/download/Modflow6-v6.3.0+0/Modflow6.v6.3.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
